name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]

# Let the job push to GHCR with GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prep: lowercase owner and strip leading "v" from tag names
      - name: Compute image vars
        id: vars
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (main branch)
        if: github.ref_type == 'branch' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner }}/wasabi-webtop:main
            ghcr.io/${{ steps.vars.outputs.owner }}/wasabi-webtop:${{ github.sha }}

      - name: Build and push Docker image (tag)
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.owner }}/wasabi-webtop:${{ steps.vars.outputs.version }}
            ghcr.io/${{ steps.vars.outputs.owner }}/wasabi-webtop:${{ github.sha }}
            ghcr.io/${{ steps.vars.outputs.owner }}/wasabi-webtop:latest
